=== ErickVelasquezTECH/visualPROJECTS/xml/XML-ERICK/1-Ejercicios-DTD/4-videolibrary/videolibrary.dtd
<!ELEMENT videolibrary (movie+, series+)>

<!ELEMENT movie (title, director, year, genre+, duration, synopsis?, cast?)>
<!ELEMENT series (title, seasons, total_episodes, current_season?, is_active, network? )>

<!ELEMENT title (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT cast (actor+)>
<!ELEMENT actor (name, character)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT character (#PCDATA)>

<!ELEMENT seasons (#PCDATA)>
<!ELEMENT total_episodes (#PCDATA)>
<!ELEMENT current_season (#PCDATA)>
<!ELEMENT is_active (#PCDATA)>
<!ELEMENT network (#PCDATA)>

<!ATTLIST movie id ID #REQUIRED
                original_language CDATA #IMPLIED
                rating CDATA #REQUIRED
                award_winner (yes|no) #IMPLIED>
<!ATTLIST series id ID #REQUIRED
                streaming_platform CDATA #REQUIRED
                country_of_origin CDATA #IMPLIED>

=== ErickVelasquezTECH/visualPROJECTS/XML-ERICK/1-Ejercicios-DTD/4-videolibrary/videolibrary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videolibrary SYSTEM "videolibrary.dtd">
<videolibrary>
  <movie id="mov001" original_language="español" rating="R" award_winner="yes">
    <title>El laberinto del fauno</title>
    <director>Guillermo del Toro</director>
    <year>2006</year>
    <genre>Fantasía oscura</genre>
    <genre>Drama histórico</genre>
    <duration>118 minutos</duration>
    <synopsis>En la España de 1944, una niña se traslada con su madre enferma...</synopsis>
    <cast>
      <actor>
        <name>Ivana Baquero</name>
        <character>Ofelia</character>
      </actor>
      <actor>
        <name>Sergi López</name>
        <character>Capitán Vidal</character>
      </actor>
    </cast>
  </movie>

  <movie id="mov002" rating="PG-13">
    <title>Los lunes al sol</title>
    <director>Fernando León de Aranoa</director>
    <year>2002</year>
    <genre>Drama social</genre>
    <duration>113 minutos</duration>
    <!-- synopsis y cast son opcionales, no están aquí -->
  </movie>

  <series id="ser001" streaming_platform="Movistar+" country_of_origin="España">
    <title>La que se avecina</title>
    <seasons>15</seasons>
    <total_episodes>239</total_episodes>
    <current_season>16</current_season>
    <is_active>Sí</is_active>
    <network>Telecinco</network>
  </series>

  <series id="ser002" streaming_platform="Netflix">
    <title>Las chicas del cable</title>
    <seasons>6</seasons>
    <total_episodes>42</total_episodes>
    <!-- current_season es opcional -->
    <is_active>No</is_active>
    <!-- network es opcional -->
  </series>
</videolibrary>
