=== ErickVelasquezTECH/visualPROJECTS/xml/ExamenXMLErick/catalogo/catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://erick.es/cat"
    xmlns:cat="http://erick.es/cat"
    elementFormDefault="qualified">

    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="10">
                <xs:element name="categoria">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="50">
                            <xs:element name="producto" type="cat:productoType"/>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="tienda" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>



    <xs:complexType name="productoType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
            <xs:element name="precio" type="cat:precioType"/>
            <xs:element name="especificaciones" type="cat:especificacionesType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="codigo" type="cat:codigoType" use="required"/>
        <xs:attribute name="stock" type="cat:stockType" use="optional"/>
    </xs:complexType>

    <xs:complexType name="precioType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="moneda" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="EUR"/>
                            <xs:enumeration value="USD"/>
                            <xs:enumeration value="GBP"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="especificacionesType">
        <xs:sequence minOccurs="0" maxOccurs="10">
            <xs:element name="espec">                                                           
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="nombre" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:simpleType name="codigoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="P[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    
    <xs:simpleType name="stockType">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"/>
            <xs:maxExclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>


    
</xs:schema>

=== ErickVelasquezTECH/visualPROJECTS/xml/ExamenXMLErick/catalogo/catalogo-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
EJERCICIO 3 (2 PUNTOS)

Crea catalogo.xsd para que se valide el siguiente XML y cumpla con las restricciones indicadas a continuación.

RESTRICCIONES PARA EL XSD:
- Raíz: catalogo con atributo tienda obligatorio
- De 1 a 10 elementos categoria
- Cada categoria tiene:
    - Atributo nombre obligatorio
    - De 1 a 50 producto
- Cada producto tiene:
    - Atributos: codigo (obligatorio), stock (opcional)
    - codigo debe tener un patrón: P seguido de 3 dígitos.
    - stock debe ser un entero entre 0 y 1000.
    - Elementos en orden: nombre (obligatorio), descripcion (opcional), precio (obligatorio), especificaciones (opcional)
    - precio tiene atributo moneda obligatorio (posibles valores: EUR, USD, GBP).
    - especificaciones contiene 0-n espec con atributo nombre obligatorio

NOTAS: Tienes que hacer al menos 3 tipos con nombre aplicados a elementos o atributos.
-->
<catalogo xmlns="http://erick.es/cat"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://erick.es/cat catalogo.xsd"
        tienda="TechStore">
    <categoria nombre="Electrónica">
        <producto codigo="P001" stock="25">
            <nombre>Portátil Pro</nombre>
            <descripcion>16GB RAM, 512GB SSD</descripcion>
            <precio moneda="EUR">899.99</precio>
            <especificaciones>
                <espec nombre="procesador">Intel i7</espec>
                <espec nombre="ram">16GB</espec>
            </especificaciones>
        </producto>
        <producto codigo="P002" stock="10">
            <nombre>Tablet Lite</nombre>
            <precio moneda="EUR">249.50</precio>
        </producto>
    </categoria>
    <categoria nombre="Libros">
        <producto codigo="P003" stock="3">
            <nombre>XML Avanzado</nombre>
            <precio moneda="USD">45.99</precio>
        </producto>
    </categoria>
</catalogo>
