=== ErickVelasquezTECH/visualPROJECTS/xml/XML-ERICK/1-Ejercicios-DTD/3-library/library.dtd
<!ELEMENT library (book+)>
<!ELEMENT book (title, author, publication, isbn, price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (firstname, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT publication (publisher, year)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!ATTLIST book id ID #REQUIRED 
            available (yes|no) #REQUIRED
            language (es|en|fr) "es"
            format CDATA #REQUIRED>

=== ErickVelasquezTECH/visualPROJECTS/xml/XML-ERICK/1-Ejercicios-DTD/3-library/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <book id="A78Z" available="no" language="es" format="ebook">
        <title>Han cantado bingo</title>
        <author>
            <firstname>Lana</firstname>
            <lastname>Corujo</lastname>
        </author>

        <publication>
            <publisher>asdf</publisher>
            <year>2025</year>
        </publication>
        <isbn>asdf</isbn>
        <price>987</price>
    </book>
</library>
