=== ErickVelasquezTECH/visualPROJECTS/XML-ERICK/Ejercicios/1-unions/unions.dtd
<!ELEMENT unions (union+)>
<!ELEMENT union 
(name*, number-affiliated,headquarter,sectors,(spokesman|spokesperson)+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT number-affiliated (#PCDATA)>
<!ELEMENT headquarter (#PCDATA)>
<!ELEMENT sectors (sector+)>
<!ELEMENT sector (name, city)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT spokesman (#PCDATA)>
<!ELEMENT spokesperson (#PCDATA)>

<!ATTLIST union id ID #REQUIRED>
<!ATTLIST union language (es|en|fr) #REQUIRED>
<!ATTLIST union country CDATA "Spain">


<!ENTITY city "Madrid">

=== ErickVelasquezTECH/visualPROJECTS/XML-ERICK/Ejercicios/1-unions/unions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE unions SYSTEM "unions.dtd">


<unions>
    <union id="a53" language="fr" country="UK">
        <name>CGT</name>
        <number-affiliated>1200</number-affiliated>
        <headquarter>C/ Trévere 25</headquarter>
        <sectors>
            <sector>
                <name>Enseñanza&lt;Secundaria&gt;</name>
                <!-- Enseñanza<Secundaria> -->
                <city>&city;</city>
            </sector>
        </sectors>
        <spokesperson>Víctor</spokesperson>
    </union>
    <union id="a54" language="es">
        <name>CCOO</name>
        <number-affiliated>1300</number-affiliated>
        <headquarter>C/ Pez 8</headquarter>
        <sectors>
            <sector>
                <name>Enseñanza</name>
                <city>Madrid</city>
            </sector>
        </sectors>
        <spokesperson>Víctor</spokesperson>
    </union>
    <union id="e53" language="en" country="UK">
        <number-affiliated>1200</number-affiliated>
        <headquarter>C/ Trévere 25</headquarter>
        <sectors>
            <sector>
                <name>Enseñanza&lt;Secundaria&gt;</name>
                <!-- Enseñanza<Secundaria> -->
                <city>&city;</city>
            </sector>
        </sectors>
        <spokesman>Víctor</spokesman>
        <spokesperson>Otro</spokesperson>
    </union>
</unions>
