=== ErickVelasquezTECH/visualPROJECTS/XML-ERICK/Ejercicios/2-grades/grades.dtd
<!ELEMENT grades (student+)>
<!ELEMENT student (name, average, subjects)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT average (#PCDATA)>
<!ELEMENT subjects (subject+)>
<!ELEMENT subject (name-subject, code, grade)>
<!ELEMENT name-subject (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ATTLIST student id ID #REQUIRED>

=== ErickVelasquezTECH/visualPROJECTS/XML-ERICK/Ejercicios/2-grades/grades.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grades SYSTEM "grades.dtd">
<grades>
    <student id="a947">  <!-- id es un atributo del elemento student -->
        <name>Víctor</name>
        <average>7.8</average>
        <subjects>
            <subject>
                <name-subject>Lenguaje de marcas</name-subject>
                <code>LM</code>
                <grade>8</grade>
            </subject>
            <subject>
                <name-subject>Programación</name-subject>
                <code>PROG</code>
                <grade>8.9</grade>
            </subject>
        </subjects>
    </student>
    <student id="a948">
        <name>Ariadna</name>
        <average>7.7</average>
        <subjects>
            <subject>
                <name-subject>Programación</name-subject>
                <code>PROG</code>
                <grade>9.9</grade>
            </subject>
        </subjects>
    </student>
</grades>
