=== ErickVelasquezTECH/visualPROJECTS/XML/ExamenXMLErick/redsocial/redsocial.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://erick.es/red"
    xmlns:red="http://erick.es/red"
    elementFormDefault="qualified">


    <xs:element name="redSocial">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="usuario" type="red:usuarioType"/>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="usuarioType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="email" type="red:emailType"/>
            <xs:element name="telefono" minOccurs="0" type="red:telefonoType"/>
            <xs:element name="seguidores" minOccurs="0" type="red:seguidoresType"/>
            <xs:element name="amigos" minOccurs="0" type="red:amigostype"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="rol" type="red:rolType" default="usuario"/>
    </xs:complexType>


    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9\.]+@[a-zA-Z]+(\.[a-zA-Z]+)+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="telefonoType">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="prefijo" use="optional">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="+34"/>
                            <xs:enumeration value="+33"/>
                            <xs:enumeration value="+44"/>
                            <xs:enumeration value="+49"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="seguidoresType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

     <xs:complexType name="amigostype">
        <xs:sequence minOccurs="0" maxOccurs="20">
            <xs:element name="amigo">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF" use="required"/> <!-- No especifica si es obligatorio o opcional, asi que le puse obligatorio...-->
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="rolType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="admin"/>
            <xs:enumeration value="usuario"/>
            <xs:enumeration value="invitado"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== ErickVelasquezTECH/visualPROJECTS/xml/ExamenXMLErick/redsocial/redsocial-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
EJERCICIO 1 (2 PUNTOS)

Crea redsocial.xsd para que se valide el siguiente XML y cumpla con las restricciones indicadas a continuación.

RESTRICCIONES PARA EL XSD:
- Raíz: redSocial con atributo nombre obligatorio
- Puede haber de 1 a n usuarios.
- Cada usuario tiene:
    - Atributos: id obligatorio, rol (puede ser "admin", "usuario" o "invitado". Por defecto es "usuario")
    - Elementos en orden: nombre (obligatorio), email (obligatorio), telefono (opcional), seguidores (opcional), amigos (opcional)
    - email debe tener patrón de email válido
    - seguidores debe ser un número entre 0 y n.
    - amigos contiene 0-20 elementos amigo vacíos. El atributo ref debe ser de tipo IDREF.
    - telefono tiene como contenido un string. Su atributo prefijo (opcional) puede tener los valores +34, +33, +44 o +49. 

NOTAS: Tienes que hacer al menos 3 tipos con nombre aplicados a elementos o atributos.
-->
<redSocial xmlns="http://erick.es/red"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://erick.es/red redsocial.xsd"
        nombre="Conectados">
    <usuario id="U001" rol="admin">
        <nombre>Ana García</nombre>
        <email>ana@email.com</email>
        <telefono prefijo="+34">612345678</telefono>
        <seguidores>150</seguidores>
        <amigos>
            <amigo ref="U002"/>
        </amigos>
    </usuario>
    <usuario id="U002" rol="usuario">
        <nombre>Carlos López</nombre>
        <email>carlos@email.com</email>
        <telefono prefijo="+34">623456789</telefono>
        <seguidores>75</seguidores>
    </usuario>
</redSocial>
